const DEFAULT_CORE = 'DEFAULT_CORE'
const TEST_CORE = 'TEST_CORE'

const UPDATE_COLOR = 'UPDATE_COLOR'
const COLOR_UPDATED = 'COLOR_UPDATED'
const UPDATE_TEXT = 'UPDATE_TEXT'
const TEXT_UPDATED = 'TEXT_UPDATED'
const DEALS_DATA_REQUEST = 'DEALS_DATA_REQUEST'
const DEALS_DATA_RESPONSE = 'DEALS_DATA_RESPONSE'
const GET_DEAL_BY_ID = 'GET_DEAL_BY_ID'
const GET_DEAL_BY_NAME = 'GET_DEAL_BY_NAME'
const ON_DEALS_DATA = 'ON_DEALS_DATA'
const ON_DEAL_DATA = 'ON_DEAL_DATA'

export {
  DEFAULT_CORE,
  TEST_CORE,
  UPDATE_COLOR,
  COLOR_UPDATED,
  UPDATE_TEXT,
  TEXT_UPDATED,
  DEALS_DATA_REQUEST,
  DEALS_DATA_RESPONSE,
  GET_DEAL_BY_ID,
  GET_DEAL_BY_NAME,
  ON_DEALS_DATA,
  ON_DEAL_DATA
}
